DROP DATABASE IF EXISTS organization_db;
CREATE DATABASE organization_db;

USE organization_db;

CREATE TABLE departments (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(30) UNIQUE NOT NULL
)

CREATE TABLE roles (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(30) UNIQUE NOT NULL,
	salary DECIMAL NOT NULL,
	department_id INT,
	
	FOREIGN KEY (department_id)
	REFERENCES departments(id)
	ON DELETE SET NULL
)

CREATE TABLE employees (
	id INT AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(30) NOT NULL,
	last_name VARCHAR(30) NOT NULL,
	role_id INT DEFAULT NULL,
	manager_id INT DEFAULT NULL,
	
	FOREIGN KEY (role_id)
	REFERENCES roles(id)
	ON DELETE CASCADE,
	
	FOREIGN KEY (manager_id)
	REFERENCES employees(id)
	ON DELETE SET NULL
)
